# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '528.FlightsDemo' do
pod 'SVProgressHUD', '~> 2.0.3'
end

target '528.FlightsDemoTests' do

end

target '528.FlightsDemoUITests' do

end

